name: Application Quality Checks

on: push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-24.04
    env:
      python_version: 3.12.3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: |
          mkdir -p .mypy_cache
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure --color=always
  test:
    name: Ubuntu Tests
    needs: [lint]
    runs-on: ubuntu-24.04
    env:
      python_version: 3.12.3
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python_version }}
    - uses: actions/cache@v4
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install --with=dev
    - name: Run Tests
      run: |
        python -m poetry run berserk-downloader-test
